export const MODAL_OPEN_INGREDIENT: 'MODAL_OPEN_INGREDIENT' =
    'MODAL_OPEN_INGREDIENT'
export const MODAL_OPEN_ORDER: 'MODAL_OPEN_ORDER' = 'MODAL_OPEN_ORDER'
export const MODAL_OPEN_ORDER_INFO: 'MODAL_OPEN_ORDER_INFO' =
    'MODAL_OPEN_ORDER_INFO'
export const MODAL_CLOSE: 'MODAL_CLOSE' = 'MODAL_CLOSE'
